name: Events-API CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    test:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Build docker image
          run: |
            docker build -t events-api:latest .

        - name: Run Container
          run: |
            docker run -d -p 5005:5005 --name events-api-container events-api:latest
            sleep 5
            curl http://localhost:5005/api/health || exit 1

        - name: Setup Python
          uses: actions/setup-python@v3
          with:
            python-version: 3.11

        - name: Install dependencies
          run: |
            pip install -r requirements.txt

        - name: Run Unit test
          run: |
            pytest -v

        - name: Clean up
          if: always()
          run: |
            docker stop events-api-container || true
            docker rm events-api-container || true